spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_TOKEN}
spring.data.redis.ssl.enabled=true

tmdb.api.key=${TMDB_KEY}
tmdb.base.url=https://api.themoviedb.org/3
tmdb.img.url=https://image.tmdb.org/t/p/w500


socketio.host=0.0.0.0
socketio.port=9092

app.jwt.secret=${JWT_SECRET_KEY}

logging.level.org.springframework.security=DEBUG